AWSTemplateFormatVersion: '2010-09-09'

Parameters:
    Zone:
        Type: String
        MinLength: 1

    Domain:
        Type: String
        MinLength: 1

    CertificateARN:
        Type: String
        MinLength: 1

    CertificateValidationDomain:
        Type: String
        MinLength: 1

    CertificateValidationValue:
        Type: String
        MinLength: 1

Resources:

    Redirectinator:
        Type: AWS::Lambda::Function
        Properties:
            Description: Redirect at the edge
            Code:
                ZipFile: !Sub |
                    'use strict';
                    const where = 'https://gregwiley.com';
                    const response = {
                        status: '302',
                        statusDescription: 'Found',
                        headers: {
                            location: [{
                                key: 'Location',
                                value: where
                            }],
                        }
                    };
                    exports.handler = (evt, ctx, cb) => {
                      cb(null, req)
                    };
            Handler: index.handler
            MemorySize: 128
            Role: !GetAtt RedirectinatorExecRole.Arn
            Runtime: nodejs6.10

    RedirectinatorVersion2:
        Type: AWS::Lambda::Version
        Properties:
            FunctionName: !Ref Redirectinator

    RedirectinatorExecRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Effect: Allow
                    Principal:
                        Service:
                          - edgelambda.amazonaws.com
                          - lambda.amazonaws.com
                    Action:
                        - sts:AssumeRole


    Edge:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Aliases:
                  - !Ref Domain
                DefaultCacheBehavior:
                    Compress: false
                    AllowedMethods: ["HEAD","GET"]
                    ForwardedValues:
                        QueryString: false
                    TargetOriginId: redirectinator
                    ViewerProtocolPolicy: redirect-to-https
                    LambdaFunctionAssociations:
                      - EventType: viewer-request
                        LambdaFunctionARN: !Ref RedirectinatorVersion2
                Enabled: true
                HttpVersion: http2
                Origins:
                  - DomainName: "nowhere39203490234.com"
                    Id: redirectinator
                    CustomOriginConfig:
                        OriginProtocolPolicy: http-only
                ViewerCertificate:
                    AcmCertificateArn: !Ref CertificateARN
                    SslSupportMethod: sni-only

    DNS:
        Type: AWS::Route53::RecordSetGroup
        Properties:
            Comment: Supporting resource records
            HostedZoneName: !Sub ${Zone}.
            RecordSets:
              - Name: !Ref CertificateValidationDomain
                Type: CNAME
                TTL: 300
                ResourceRecords:
                  - !Ref CertificateValidationValue
              - Name: !Sub ${Domain}.
                Type: A
                AliasTarget:
                    HostedZoneId: Z2FDTNDATAQYW2
                    DNSName: !GetAtt Edge.DomainName


